

// / FIREBASE AUTH ACTIONS
export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';
export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';
export const LOGIN_FIREBASE_USER = 'LOGIN_FIREBASE_USER';
export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const FIREBASE_PASSWORD_RESET_EMAIL = 'FIREBASE_PASSWORD_RESET_EMAIL';
export const LOGOUT_FIREBASE_USER = 'LOGOUT_FIREBASE_USER';
export const GET_USER_COURSES = 'GET_USER_COURSES';
export const GET_SECTIONS = 'GET_SECTIONS';
export const ADD_USER_SECTION = 'ADD_USER_SECTION';
export const GET_EVENTS = 'GET_EVENTS';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const DELETE_COURSE = 'DELETE_COURSE';
export const IS_PROFESSOR = 'IS_PROFESSOR';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const ADD_TA = 'ADD_TA'
